kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - sleep 10
  - make test
services:
  - name: database
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test